# Generated by Django 2.2.2 on 2020-07-14 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucketadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funstatus',
            name='user_posted',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_posted2user_posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
