# Generated by Django 2.2.2 on 2020-07-15 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucketadmin', '0002_funstatus_user_posted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funpost',
            name='Profile',
        ),
        migrations.AddField(
            model_name='funpost',
            name='Img_post',
            field=models.FileField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='funpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
