# Generated by Django 2.2.2 on 2020-07-16 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bucketadmin', '0005_funpost_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funpost',
            name='liked',
        ),
    ]
