# Generated by Django 2.2.2 on 2020-07-16 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucketadmin', '0010_auto_20200716_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funpost',
            name='Liked_user',
        ),
        migrations.AlterField(
            model_name='funpost',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted', to=settings.AUTH_USER_MODEL),
        ),
    ]
