# Generated by Django 2.2.2 on 2020-07-16 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucketadmin', '0011_auto_20200716_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funpost',
            name='value',
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Like', 'Like'), ('Unlike', 'Unlike')], default='Like', max_length=10)),
                ('Post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bucketadmin.Funpost')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
