# Generated by Django 2.2.2 on 2020-07-16 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucketadmin', '0012_auto_20200716_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='funpost',
            name='liked',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
