# Generated by Django 2.2.2 on 2020-07-17 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bucketadmin', '0014_auto_20200717_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='Liked_users',
        ),
        migrations.AddField(
            model_name='status',
            name='Liked_users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
